### ISSUE TITLE
Information: friend project of mine, but for Visual Studio

### ISSUE THREAD

**Issue by algorys** [digitalist/qmake2cmake#1]
Hello,

Great to see this kind of project. I'll test it ASAP.

For your information, I maintain a similar project but for Visual Studio (.vcxproj): https://github.com/algorys/cmakeconverter.

But it's in Python. But in case, we can exchange between us... We can add a link to our README between project ?

Good luck :wink:

**Comment by digitalist** [comment]
Done! 
I have a feeling it will be more useful for me to think about adding qmake support into cmakeconverter, by the way

**Comment by algorys** [comment]
@digitalist if you want, you can. Thanks.

But currently, project is not ready for QMake. But it might be a good idea
